---
- name: Add proxy support
  template:
    src: apt_proxy_conf.j2
    dest: /etc/apt/apt.conf.d/80proxy
  when: http_proxy is defined

- name: Reconfigure apt repositories
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  when: recofigure_repositories

- name: Update apt cache
  apt:
    update_cache: yes

# Cannot upgrade via "apt" module since it depends on aptitude
- name: Upgrade system
  command: apt-get -y upgrade
  when: upgrade_system
