---
- name: Add proxy support
  template:
    src: apt_proxy_conf.j2
    dest: /etc/apt/apt.conf.d/80proxy
  when: http_proxy is defined

- name: Reconfigure apt repositories
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  when: recofigure_repositories

- name: Reload apt cache
#  command: "apt-cache update"
  apt:
    update_cache: yes

