---
- name: Check if system was provisioned with cloudinit
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloudinit

- name: disable hostname changind in cloud-init scripts
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "^preserve_hostname: false"
    line: "preserve_hostname: true"
    state: present
    backup: yes
  when: cloudinit.stat.exists

- name: change hostname in /etc/hostname (from ansible_host)
  hostname:
    name: "{{ ansible_host }}"
  when: ansible_host is defined and not ansible_host | ipaddr

- name: change hostname in /etc/hostname (from inventory)
  hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_host is undefined or ansible_host | ipaddr

- name: reload facts to pick up new hostname
  setup:

- name: change hosts in /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
