---
- block:
  - stat:
      path: /etc/cloud/cloud.cfg
    register: cloudinit
  
  - name: disable hostname changind in cloud-init scripts
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      regexp: "^preserve_hostname: false"
      line: "preserve_hostname: true"
      state: present
      backup: yes
    when: cloudinit.stat.exists
  
  - name: change hostname in /etc/hostname
    hostname:
      name: "{{ inventory_hostname }}"
  
  - name: change hostname in /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: "^127.0.0.1", line: "127.0.0.1 localhost" }
      - { regexp: "^127.0.1.1", line: "127.0.1.1 {{ inventory_hostname }}" }
  when: system_hostname

- name: append inventory hosts
  lineinfile:
    dest: /etc/hosts
#    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].inventory_hostname }}"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].inventory_hostname }}.{{ domainname }} {{ hostvars[item].inventory_hostname }}"
    regexp: ".*{{ hostvars[item].inventory_hostname }}$"
    state: present
  with_items: "{{ groups['all'] }}"

- name: append custom entries
  lineinfile:
    dest: /etc/hosts
#    line: "{{ item.ip }} {{ item.name }}.{{ domainname }} {{ item.name }}"
    line: "{{ item.ip }} {{ item.name }}"
    regexp: ".*{{ item.name }}$"
    state: present
  with_items: "{{ system_custom_hosts }}"
