---
- name: Check if system was provisioned with cloudinit
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloudinit

- name: disable hostname changind in cloud-init scripts
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "^preserve_hostname: false"
    line: "preserve_hostname: true"
    state: present
    backup: yes
  when: cloudinit.stat.exists

- name: change hostname in /etc/hostname
  hostname:
    name: "{{ ansible_host | default(inventory_hostname) }}"

- name: change hosts in /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
