---
- block:
  - name: Reconfigure apt repositories
    template:
      src: sources.list.j2
      dest: /etc/apt/sources.list
    when: system_recofigure_repositories

  - name: Install apt dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - aptitude
      - python-apt

  - name: Upgrade system
    apt:
      upgrade: yes
    when: system_upgrade
    register: upgrade_status
  when: ansible_pkg_mgr == "apt"

- block:
  - name: Install epel repository
    yum:
      name: epel-release
      state: installed

  # Disable linter on this task, since ANSIBLE0010 doesn't apply here
  - name: Upgrade system
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: system_upgrade
    register: upgrade_status
    tags: skip_ansible_lint
  when: ansible_pkg_mgr == "yum"

- name: Install basic software
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ system_packages }}"
  notify: start haveged

- name: Make Vim great again
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  when: ansible_pkg_mgr == "apt"
  
- name: Reboot server
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true
  when: 
    - system_upgrade
    - upgrade_status|changed
  
- name: Wait for the server to finish rebooting
  become: no
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    search_regex: "OpenSSH"
    port: 22
    timeout: 300
  when: 
    - system_upgrade
    - upgrade_status|changed
