---
- block:
  - name: Reconfigure apt repositories
    template:
      src: sources.list.j2
      dest: /etc/apt/sources.list
    when: system_recofigure_repositories

  - name: Install apt dependencies
    apt:
      name: "{{ apt_dependencies }}"
      state: present
      update_cache: yes

  - name: Upgrade system
    apt:
      upgrade: yes
    when: system_upgrade
    register: upgraded_apt
  when: ansible_pkg_mgr == "apt"

- block:
  - name: Install epel repository
    yum:
      name: epel-release
      state: installed

  # Disable linter on this task, since ANSIBLE0010 doesn't apply here
  - name: Upgrade system
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: system_upgrade
    register: upgraded_yum
    tags: skip_ansible_lint
  when: ansible_pkg_mgr == "yum"

- name: Install basic software
  package:
    name: "{{ system_packages }}"
    state: present
  notify: start haveged

- name: Make Vim great again
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  when: ansible_pkg_mgr == "apt"

- meta: flush_handlers
