---
- name: SSH run directory
  file:
    path: /var/run/sshd
    state: directory
    mode: 0755
  when: ansible_distribution|lower == "ubuntu"

- name: Add warning before SSH login
  template:
    src: banner.txt.j2
    dest: "/etc/ssh/banner.txt"

- name: Start SSH service
  service:
    name: "{{ system_sshd_service }}"
    enabled: true
    state: started
