---
- name: disable IPv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
  when: system_disable_ipv6

- name: tune network performace
  sysctl:
    name: "{{ item.var }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
  with_items:
    - { var: "net.core.somaxconn", value: "{{ system_max_conn }}" }
    - { var: "net.ipv4.tcp_max_syn_backlog", value: "{{ system_syn_backlog }}" }
    - { var: "net.ipv4.tcp_tw_reuse", value: "{{ system_tw_reuse }}" }
    - { var: "net.ipv4.tcp_tw_recycle", value: "{{ system_tw_recycle }}" }
  ignore_errors: true

- name: additional sysctl options
  sysctl:
    name: "{{ item.var }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
  with_items: "{{ system_sysctl }}"
