---
- name: restart yum-cron
  systemd:
    name: yum-cron
    state: restarted
    enabled: yes

- name: start haveged
  systemd:
    name: haveged
    state: started
    enabled: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
