---
- name: restart yum-cron
  service:
    name: yum-cron
    state: restarted
    enabled: yes

- name: start haveged
  service:
    name: haveged
    state: started
    enabled: yes

- name: restart journald
  service:
    name: systemd-journald
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  when: ansible_os_family == "Debian"
